= PCF & Docker -- Twitter Sentiment

== Description

This application analyzes and streams sentiment from a Twitter hash tag. Its aim is to show the same exact code, and repository content can be used to push an app into cloud foundry, as well as build a Docker container, thereby showing that the Docker container is a redundant step which takes time for building updated versions of the app image.

== Project SetUp

. Obtain Twitter Application keys from https://apps.twitter.com

To build you own Docker image from this demo it is recommended to create a DockerHub registry account, and create an automated build from a forked version of this repo.

. Fork this repo to your own GitHub account
. Create a link:https://hub.docker.com[DockerHub] registry account
. Create an automated build of your forked repo: https://docs.docker.com/docker-hub/builds/

== Execution

Run this repo either as a standalone PCF app, or as a Docker image pushed to PCF.

=== Cloud Foundry

. Open the Manifest file, modify the parameters and environment variables for your deployment
+ 
$ cf push -f manifest.yml 

=== Cloud Foundry via DockerHub

. Open the Dockerfile, note the dummy environment variables (do not change)
. Push the app into PCF
+
$ cf docker-push twitter-sentiment bbertka/ltc-twitter-sentiment-demo

(Use your own account and image name for the deploy)


